<?php

namespace Vladitot\Architect\Yaml\Laravel;

use Spatie\LaravelData\Data;

class ModelField extends Data
{
    public string $title;
    public ?string $additional_migration_argument;

    /**
     * @var string $field_type
     * @autocompleteFunction getFieldTypes
     */
    public string $field_type;

    /**
     * @var string $faker_value
     * @autocompleteFunction getFakerValues
     */
    public string $faker_value;

    public ?string $faker_arguments;

    public ?bool $nullable;

    public ?string $default;

    public static function getFakerValues() {
        return [
            'citySuffix',
            'streetSuffix',
            'buildingNumber',
            'city',
            'streetName',
            'streetAddress',
            'postcode',
            'address',
            'country',
            'latitude',
            'longitude',
            'localCoordinates',
            'randomDigitNotNull',
            'passthrough',
            'randomLetter',
            'randomAscii',
            'randomElements',
            'randomElement',
            'randomKey',
            'shuffle',
            'shuffleArray',
            'shuffleString',
            'numerify',
            'lexify',
            'bothify',
            'asciify',
            'regexify',
            'toLower',
            'toUpper',
            'biasedNumberBetween',
            'hexColor',
            'safeHexColor',
            'rgbColorAsArray',
            'rgbColor',
            'rgbCssColor',
            'rgbaCssColor',
            'safeColorName',
            'colorName',
            'hslColor',
            'hslColorAsArray',
            'company',
            'companySuffix',
            'jobTitle',
            'unixTime',
            'dateTime',
            'dateTimeAD',
            'iso8601',
            'date',
            'time',
            'dateTimeBetween',
            'dateTimeInInterval',
            'dateTimeThisCentury',
            'dateTimeThisDecade',
            'dateTimeThisYear',
            'dateTimeThisMonth',
            'amPm',
            'dayOfMonth',
            'dayOfWeek',
            'month',
            'monthName',
            'year',
            'century',
            'timezone',
            'file',
            'randomHtml',
            'imageUrl',
            'image',
            'email',
            'safeEmail',
            'freeEmail',
            'companyEmail',
            'freeEmailDomain',
            'safeEmailDomain',
            'userName',
            'password',
            'domainName',
            'domainWord',
            'tld',
            'url',
            'slug',
            'ipv4',
            'ipv6',
            'localIpv4',
            'macAddress',
            'word',
            'words',
            'sentence',
            'sentences',
            'paragraph',
            'paragraphs',
            'text',
            'boolean',
            'md5',
            'sha1',
            'sha256',
            'locale',
            'countryCode',
            'countryISOAlpha3',
            'languageCode',
            'currencyCode',
            'emoji',
            'creditCardType',
            'creditCardNumber',
            'creditCardExpirationDate',
            'creditCardExpirationDateString',
            'creditCardDetails',
            'iban',
            'swiftBicNumber',
            'name',
            'firstName',
            'firstNameMale',
            'firstNameFemale',
            'lastName',
            'title',
            'titleMale',
            'titleFemale',
            'phoneNumber',
            'e164PhoneNumber',
            'imei',
            'realText',
            'realTextBetween',
            'macProcessor',
            'linuxProcessor',
            'userAgent',
            'chrome',
            'msedge',
            'firefox',
            'safari',
            'opera',
            'internetExplorer',
            'windowsPlatformToken',
            'macPlatformToken',
            'iosMobileToken',
            'linuxPlatformToken',
            'uuid',
        ];
    }
    public static function getFieldTypes() {
        return [
            'bigIncrements',
            'bigInteger',
            'binary',
            'boolean',
            'char',
            'dateTimeTz',
            'dateTime',
            'date',
            'decimal',
            'double',
            'enum',
            'float',
            'foreignId',
            'foreignIdFor',
            'foreignUlid',
            'foreignUuid',
            'geometryCollection',
            'geometry',
            'id',
            'increments',
            'integer',
            'ipAddress',
            'json',
            'jsonb',
            'lineString',
            'longText',
            'macAddress',
            'mediumIncrements',
            'mediumInteger',
            'mediumText',
            'morphs',
            'multiLineString',
            'multiPoint',
            'multiPolygon',
            'nullableMorphs',
            'nullableTimestamps',
            'nullableUlidMorphs',
            'nullableUuidMorphs',
            'point',
            'polygon',
            'rememberToken',
            'set',
            'smallIncrements',
            'smallInteger',
            'softDeletesTz',
            'softDeletes',
            'string',
            'text',
            'timeTz',
            'time',
            'timestampTz',
            'timestamp',
            'timestampsTz',
            'timestamps',
            'tinyIncrements',
            'tinyInteger',
            'tinyText',
            'unsignedBigInteger',
            'unsignedDecimal',
            'unsignedInteger',
            'unsignedMediumInteger',
            'unsignedSmallInteger',
            'unsignedTinyInteger',
            'ulidMorphs',
            'uuidMorphs',
            'ulid',
            'uuid',
            'year',
        ];
    }
}
